trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v2_9_1_VOICE.zip'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v2_9_1_VOICE.zip'

jobs:

#- template: Android/build-template/build-android.yml
#  parameters:
#    project: 'Android'
#    module: 'sample-custom-recorder'
#    name: 'CustomRecorder'

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraRTCWithASMR'
    workingDirectory: 'iOS&macOS/Agora-RTC-With-ASMR'
    scheme: 'Agora-RTC-With-ASMR'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraRTCWithVoiceChangeriOS'
    workingDirectory: 'iOS&macOS/Agora-RTC-With-Voice-Changer-iOS'
    scheme: 'Agora-RTC-With-Voice-Changer-iOS'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraAudioIOiOS'
    workingDirectory: 'iOS&macOS/AgoraAudioIO-Objective-C'
    scheme: 'AgoraAudioIO-iOS'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-mac.yml
  parameters:
    displayName: 'AgoraAudioIOmacOS'
    workingDirectory: 'iOS&macOS/AgoraAudioIO-Objective-C'
    scheme: 'AgoraAudioIO-macOS'
    sdkurl: $(MacRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'PronunciationAssess'
    workingDirectory: 'iOS&macOS/Pronunciation-Assess-iOS'
    scheme: 'Pronunciation-Assess'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'SpeechRecognizeriOS'
    workingDirectory: 'iOS&macOS/SpeechRecognizer-iOS'
    scheme: 'SpeechRecognizer-iOS'
    sdkurl: $(iOSRTCSDK)
