trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

variables:
- group: AgoraKeys

jobs:

- template: Advanced-Audio-Android/build-templates/build-android.yml
  parameters:
    project: 'Advanced-Audio-Android'
    module: 'custom-recorder'
    name: 'CustomRecorder'